package com.example.futbolappscaffidiruderman

class futbolProvider {

    companion object{
        val clubesList= listOf<Futbol>(
            Futbol("Real Madrid", "La Liga", "España", "https://logos-world.net/wp-content/uploads/2020/06/Real-Madrid-Logo-1997-2001.jpg", "El Real Madrid Club de Fútbol es un club polideportivo de la ciudad de Madrid, España. Fundado el 6 de marzo de 1902 como Sociedad Madrid Foot-Ball Club, en su rama futbolística - que juega en la Primera División de España - fue denominado por la FIFA el Mejor Club del Siglo XX."),
            Futbol("Barcelona", "La Liga", "España", "https://logos-world.net/wp-content/uploads/2020/04/Barcelona-Emblem.jpg", "El Fútbol Club Barcelona (en catalán: Futbol Club Barcelona), conocido popularmente como Barça,n. 1 es una entidad polideportiva con sede en Barcelona, Cataluña, España. Fue fundado como club de fútbol el 29 de noviembre de 1899 y registrado oficialmente el 5 de enero de 1903."),
            Futbol("River Plate", "Liga Argentina", "Argentina", "https://brandemia.org/contenido/subidas/2022/02/000-river-plate.jpg", "River Plate es el club más popular de la República Argentina, con más de 100.000 socios, más de 18 millones de hinchas en el país y miles en cada rincón del mundo. La Institución cuenta con 36 títulos nacionales (el más ganador) y 12 copas internacionales."),
            Futbol("Boca Juniors", "Liga Argentina", "Argentina", "https://logowik.com/content/uploads/images/ca-boca-juniors3155.jpg", "El Club Atlético Boca Juniors es una institución argentina que posee su sede en el barrio de La Boca, Buenos Aires. Fue fundado el 3 de abril de 1905 y desde el año 1913 participa ininterrumpidamente de la Primera División del fútbol argentino."),
            Futbol("Manchester City", "Premier League", "Inglaterra", "https://thumbs.dreamstime.com/b/logotipo-de-manchester-city-127684756.jpg", "El Manchester City fue fundado un 23 de noviembre de 1880 bajo el nombre de St. Marks'. Su denominación final tal y como la conocemos hoy en día se produjo un 16 de abril de 1894. El City, hoy en día, es considerado uno de los grandes de Inglaterra y Europa."),
            Futbol("Manchester United", "Premier League", "Inglaterra", "https://i.ebayimg.com/images/g/QsMAAOSwuJFeNPFp/s-l1200.webp", "El Manchester United Football Club, conocido como Manchester United o simplemente United, es un club de fútbol profesional inglés de la ciudad de Mánchester, Inglaterra, que compite en la Premier League. Disputa sus partidos como local en el estadio Old Trafford, desde 1910."),
            Futbol("Borussia Dortmund", "Bundesliga", "Alemania", "https://logos-world.net/wp-content/uploads/2020/11/Borussia-Dortmund-Logo-2012-present.jpg", "El Borussia Dortmund (oficialmente en alemán Ballspielverein Borussia 09 e.V. Dortmund, y comúnmente BVB, o Borussia Dortmund pronunciado /boˈʁʊsi̯a ˈdɔʁtmʊnt/ bajo la identidad corporativa Borussia Dortmund GmbH & Co. KGaA, es una entidad deportiva profesional sita en Dortmund, en la región Rin-Ruhr del estado federal de Renania del Norte-Westfalia, Alemania. Fue fundada el 19 de diciembre de 1909 como un club de fútbol, actividad por la que es principalmente conocido y en la que llegó a situarse como el segundo equipo más laureado del país."),
            Futbol("Bayern Munich", "Bundesliga", "Alemania", "https://wallpaper-mania.com/wp-content/uploads/2018/09/High_resolution_wallpaper_background_ID_77701984241.jpg", "El Bayern de Múnich fue fundado el veintisiete de febrero de 1900 en Munich. Es el club de fútbol más laureado en la historia de Alemania, y es considerado coo uno de los más grandes de Europa."),
            Futbol("Lazio", "Serie A", "Italia", "https://logos-world.net/wp-content/uploads/2020/06/Lazio-Logo-1993-1998.jpg", "Fue fundado el 9 de enero de 1900 y juega en la Serie A de Italia. Utiliza camiseta celeste con pantalón blanco, y juega de local en el Estadio Olímpico de Roma, el segundo estadio más grande de Italia, únicamente por detrás de San Siro. Su histórico rival es el otro equipo de la capital italiana, la A.S."),
            Futbol("Milan", "Serie A", "Italia", "https://1000marcas.net/wp-content/uploads/2020/02/AC-Milan-Logo.jpg", "La Associazione Calcio Milan es un club de fútbol de la ciudad de Milán, región de Lombardía, Italia. Fue fundado el 16 de diciembre de 1899 por Alfred Edwards, juega de local en el estadio San Siro desde el año 1926, y viste camiseta roja y negra a franjas verticales con pantalón blanco."),)
    }

}